name = "ants-api"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-12-18"

[vars]
QDRANT_URL = "https://a5ec859b-6b38-4a39-a3ac-dc73da43c911.eu-central-1-0.aws.cloud.qdrant.io:6333"

[observability]
enabled = true